services:
  server:
    build: ./server
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - database

  client:
    build: ./client
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules # Mask node_modules to prevent conflicts between host and container
    ports:
      - "5173:5173"
    depends_on:
      - server

  database:
    container_name: postgresql_database
    image: postgres:18
    restart: unless-stopped
    env_file:
      - project.env
  
  database-migrations:
    image: flyway/flyway:12
    env_file:
      - project.env
    depends_on:
      - database
    volumes:
      - ./database-migrations:/flyway/db/migration
    command: -connectRetries=60 -baselineOnMigrate=true migrate
