services:
  server:
    build: ./server
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"

  client:
    build: ./client
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules # Mask node_modules to prevent conflicts between host and container
    ports:
      - "5173:5173"

  database:
    container_name: postgresql_database
    image: postgres:18
    restart: unless-stopped
    env_file:
      - project.env
      